server:
  port: 8081
spring:  cloud:    config:      server:        git:          uri: https://github.com/Kishor-C/config-server.git
management:  endpoints:    web:      exposure:        include: "*"