server:
  port: 9090
  servlet:    context-path: /spring-boot-rest
    
spring:  datasource:    url: jdbc:mysql://localhost:3306/connvertex
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root